name = "Algames"
uuid = "4a64a370-b39e-4988-9b44-fc3fb6d78c25"
authors = ["simon-lc <simonlc@stanford.edu>"]
version = "0.1.5"

[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"

[compat]
Altro = "0.3.0 - 0.3.0"
BenchmarkTools = "0.5"
ForwardDiff = "0.10"
GeometryBasics = "0.3"
Parameters = "0.12"
RobotDynamics = "0.3.1 - 0.3.1"
StaticArrays = "1.0"
TrajectoryOptimization = "0.4.1 - 0.4.1"
julia = "1"
